sudo: required
services:
    - docker

before_install:
    - docker build -t max13j/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true max13j/react-test npm test

after_success:
    - docker build -t max13j/multi-client ./client
    - docker build -t max13j/multi-nginx ./nginx
    - docker build -t max13j/multi-server ./server
    - docker build -t max13j/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images an push it to docker hub
    - docker push max13j/multi-client
    - docker push max13j/multi-nginx
    - docker push max13j/multi-server
    - docker push max13j/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-dockerenv: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-602336792304
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY